services:
  gamebottest:
    image: gamebottest
    build:
      context: .
      dockerfile: GameBotTest/Dockerfile
    env_file: .env
    ports:
      - "5141:5140"
    environment:
      GameApi: http://gameapi:8080
  gameapi:
    image: gameapi
    build:
      context: .
      dockerfile: GameAPI/Dockerfile
    env_file: .env
    ports:
      - "5000:8080"
    depends_on:
      - mongo
      - redis
  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - "27018:27017"
      volumes:
        - mongo-data:/data/db
  redis:
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"

volumes:
  mongo-data: